CREATE DATABASE IF NOT EXISTS gra_browserowa CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
USE gra_browserowa;

CREATE TABLE IF NOT EXISTS players (
    id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    nick VARCHAR(24) NOT NULL UNIQUE,
    password_hash VARCHAR(255) NOT NULL,
    avatar_path VARCHAR(255) DEFAULT NULL,
    level INT UNSIGNED NOT NULL DEFAULT 1,
    xp BIGINT UNSIGNED NOT NULL DEFAULT 0,
    money BIGINT UNSIGNED NOT NULL DEFAULT 0,
    aim INT UNSIGNED NOT NULL DEFAULT 10,
    refleks INT UNSIGNED NOT NULL DEFAULT 10,
    mobilnosc INT UNSIGNED NOT NULL DEFAULT 10,
    kontrola_odrzutu INT UNSIGNED NOT NULL DEFAULT 10,
    granaty INT UNSIGNED NOT NULL DEFAULT 10,
    szczescie INT UNSIGNED NOT NULL DEFAULT 10,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);
